### ISSUE TITLE
the banner image and text should be vertically centered

### ISSUE THREAD

**Issue by Shruti3004** [winterofcode/winterofcode2020#3]
![Screenshot from 2021-02-26 05-13-01](https://user-images.githubusercontent.com/56133783/109234359-8eb54480-77f1-11eb-87c1-19c9fb640b67.png)

**Comment by xprilion** [comment]
Hi @Shruti3004, any particular reason why you feel it should be vertically centered?

**Comment by Shruti3004** [comment]
Hey @xprilion, from UI prespective it will give a better look to the site.

**Comment by xprilion** [comment]
I think the issue appears on devices with larger screens ( I was able to replicate it by zooming out a lot)

@vishwajeetraj11 can you please take a look? I believe the issue is well found (kudos to @Shruti3004 🎉  ) and we should plan around solving it.

**Comment by vishwajeetraj11** [comment]
Sure, will fix that.

**Comment by xprilion** [comment]
@Shruti3004 would you like to send in a fix for this?

**Comment by vishwajeetraj11** [comment]
I fixed it. most probably. 🙂

**Comment by xprilion** [comment]
@vishwajeetraj11 can you please link the fix PR with this issue? (Use the Fixes notation on the PR) 

Also, I am still able to replicate the issue. Can you please check?
